version: '2'
services:
  database:
    container_name: isf_database
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=isf
      - POSTGRES_PASSWORD=isf
      - POSTGRES_DB=isf
  nginx:
    container_name: isf_nginx
    image: nginx:1.13.6-alpine
    ports:
      - "8080:80"
    depends_on:
      - fpm
    volumes_from:
      - fpm:ro
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  fpm:
    container_name: isf_fpm
    build:
      context: ./docker/php
      args:
        uid: 1000
        gid: 1000
    depends_on:
      - database
    volumes:
      - ~/.composer:/home/www-data/.composer
      - ~/.ssh:/home/www-data/.ssh:ro
      - .:/srv
  rust:
    container_name: isf_rust
    image: rust:1.26-jessie
    depends_on:
      - database
    volumes:
      - ./rust:/usr/src/myapp
      - /tmp/registry:/usr/local/cargo/registry
